# You may want to uninstall overcommit if you encountered issues when rebasing
verify_signatures: false

PreCommit:
  FixMe:
    enabled: true
  Rubocop:
    enabled: true
    command: ["bin/rubocop", "--parallel"]
  SolargraphTypeCheck:
    enabled: true
    command: ["scripts/solargraph-typecheck"]

CommitMsg:
  CapitalizedSubject:
    enabled: false
  TrailingPeriod:
    enabled: false
  SingleLineSubject:
    enabled: false
  TextWidth:
    enabled: true
