version: "3.7"

# Steps:
# 1. bundle install
# 2. bundle package
# 3. docker-compose up --build
services:
  app:
    command: bin/rdebug-ide --host 0.0.0.0 --port ${DEBUG_PORT} -- bin/rails s -p ${PORT} -b 0.0.0.0
    container_name: app
    build:
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/log
      - node_modules:/app/node_modules
      - bundle:/bundle
    ports:
      - ${DEBUG_PORT}:${DEBUG_PORT}
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - postgres
    networks:
      - webnet

  redis:
    container_name: redis
    image: redis
    networks:
      - webnet

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:

volumes:
  bundle:
  node_modules:
  pgdata:
