name: Push Docker Image

on:
  release:
    types:
      - created

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker Image
        uses: HurricanKai/Publish-Docker-Github-Action@master
        # if: contains(github.ref, 'refs/tags/v')
        with:
          name: robturtle/scaffold-rails
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tagging: true
          cache: true
