name: Deploy

on:
  release:
    types:
      - created
    branches:
      - website

env:
  DOKKU_HOST: "liu-backend.com"
  DOKKU_APP_NAME: "rails"
  DOKKU_REMOTE_BRANCH: "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        uses: woudsma/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}
          dokku-host: ${{ env.DOKKU_HOST }}
          app-name: ${{ env.DOKKU_APP_NAME }}
          app-remote-branch: ${{ env.DOKKU_REMOTE_BRANCH }}
